### ISSUE TITLE
Footern länkar till gammal source.php

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/javascript#2]
Varje footer i varje lekplats-exempel länkar till source.php som inte existerar. Exempel:
https://github.com/dbwebb-se/javascript/blob/master/example/lekplats/mall/footer.php#L3

```
$srcUrl = '../source.php?dir=' . end($d) . '&amp;file=' . basename($_SERVER["PHP_SELF"]) . '#file';
```

Kanske borde ersättas med länkar till Github istället? Exempel:

```
$srcUrl = 'https://github.com/dbwebb-se/javascript/blob/master/example/lekplats' . end($d) . '&amp;file=' . basename($_SERVER["PHP_SELF"]);
```

**Comment by mosbth** [comment]
Jao, det är en bra idé att ersätta länkarna till source.php med github. Dessa exempel kom till innan jag började använda github i större omfattning.

Men jag valde att lägga till en kopia av source.php istället. Det blev mindre att ändra och färre eventuella följdfel.
